### PR TITLE
Bugfix: qemu -append flag only works when -kernel is used

### PR DESCRIPTION
**Pull request by stapelberg**

### CODE REVIEW

**Comment by stapelberg** [comment]
Friendly ping @anatol? This seems simple enough to me, and unblocks committing my test :)

**Comment by anatol** [comment]
Sorry missed the email notification. The change looks good to me. Thanks for it.

**Comment by anatol** [comment]
Actually looking closely at the there is already the parameters check just a few lines above

```go
if opts.Kernel == "" && len(opts.Append) > 0 {
    // it comes from QEMU "qemu-system-x86_64: -append only allowed with -kernel option"
    return nil, fmt.Errorf("opts.Append only allowed with opts.Kernel option")
}
```

So if you have `len(kernelArgs) > 0` and `Kernel == ""` it means that it was added by

```
if opts.OperatingSystem == OS_LINUX {
    kernelArgs = append(kernelArgs, "console=ttyS0,115200", "ignore_loglevel")
}
```

Does it means that you set `OperatingSystem` to linux but you don't have `Kernel`?

**Comment by stapelberg** [comment]
> Does it means that you set `OperatingSystem` to linux but you don't have `Kernel`?

Yep: https://github.com/gokrazy/gokrazy/commit/9dfaae9552585a4479fc4ad030148d69693a52a8

The point of my test is to verify that booting my image via UEFI works, so I must not specify `Kernel` when starting qemu.

**Pull request merged**
